### ISSUE TITLE
[IOError: Failed to interpret file 'models/srl-class-predicates.npz' as a pickle] Error while running nlpnet-test.py

### ISSUE THREAD

**Issue by bakszero** [erickrf/nlpnet#39] opened 2018-07-30 18:23 UTC
I'm facing an issue while doing predicate detection with trained SRL models on a new language.
nlpnet-train.py is able to train succesfully. But, when I run the standalone command with :
`nlpnet-test.py srl -v --gold outputs/projected/1final_nlpnet.data --data models/ --preds`

I get the following error:
`/home/baks/GSOC/ENV/local/lib/python2.7/site-packages/h5py/__init__.py:36: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from ._conv import register_converters as _register_converters
/home/baks/GSOC/ENV/local/lib/python2.7/site-packages/h5py/__init__.py:45: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from . import h5a, h5d, h5ds, h5f, h5fd, h5g, h5r, h5s, h5t, h5p, h5z
/home/baks/GSOC/ENV/local/lib/python2.7/site-packages/h5py/_hl/group.py:22: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  from .. import h5g, h5i, h5o, h5r, h5t, h5l, h5p
Loading network
Traceback (most recent call last):
  File "/home/baks/GSOC/ENV/bin/nlpnet-test.py", line 710, in <module>
    evaluate_srl_predicates(args.gold)
  File "/home/baks/GSOC/ENV/bin/nlpnet-test.py", line 515, in evaluate_srl_predicates
    nn = taggers.load_network(md)
  File "/home/baks/GSOC/ENV/local/lib/python2.7/site-packages/nlpnet/taggers.py", line 38, in load_network
    nn = net_class.load_from_file(md.paths[md.network])
  File "nlpnet/network.pyx", line 858, in nlpnet.network.Network.load_from_file (nlpnet/network.c:14604)
  File "/home/baks/GSOC/ENV/local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 443, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file 'models/srl-class-predicates.npz' as a pickle`

**Comment by erickrf** [comment] 2018-08-09 12:25
Did you use different versions of Python for training and testing? Pickle has some compatibility issues.

**Comment by jpalves** [comment] 2019-06-20 07:49
i have the same error  with python 3.6 in training the file format is not npz but a hdf5 file when in test it try to  load a npz gives the error

**Comment by erickrf** [comment] 2019-06-21 13:04
Apparently this is caused by the newest numpy version. I recommend using numpy 1.9 to 1.15.

**Comment by erickrf** [comment] 2019-08-12 15:56
This may have been the same issue as in #42 , which is fixed now. Please reopen if the error persists.

**Closed by erickrf** 2019-08-12 15:56 UTC
